services:
  dev:
    build:
      dockerfile: ./Dockerfile
      context: .
    environment:
      - TERM=${TERM}
    container_name: dev-container
    command: ["tail", "-f", "/dev/null"]
    restart: "no"
