[tools]
node = "26.3.1"
neovim = "0.12.3"
fzf = "0.73.1"
ripgrep = "15.1.0"
bat = "0.26.1"
yazi = "26.5.6"
starship = "1.25.1"
delta = "0.19.2"
lazygit = "0.62.2"
atuin = "18.16.1"
fd = "10.4.2"
zoxide = "0.10.0"
eza = "0.23.4"
vivid = "0.11.1"
tree-sitter = "0.25.10"
pi = "0.80.3"
task = "3.50.0"
direnv = "2.37.1"
glow = "2.1.2"
"aqua:fish-shell/fish-shell" = "4.8.0"
"aqua:tealdeer-rs/tealdeer" = "1.8.1"

[settings]
verbose = false      # set to true to see full installation output, see `MISE_VERBOSE`
http_timeout = "30s" # set the timeout for http requests as duration string, see `MISE_HTTP_TIMEOUT`
jobs = 4             # number of plugins or runtimes to install in parallel. The default is `4`.

experimental = false # enable experimental features
